# Generated by Django 4.2.7 on 2025-06-29 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question that users might ask', max_length=500)),
                ('answer', models.TextField(help_text="The mentor's response")),
                ('keywords', models.CharField(help_text='Comma-separated keywords for matching (e.g., startup,funding,team)', max_length=300)),
                ('category', models.CharField(choices=[('startup_basics', 'Startup Basics'), ('funding', 'Funding & Investment'), ('team_building', 'Team Building'), ('product_development', 'Product Development'), ('marketing', 'Marketing & Sales'), ('legal', 'Legal & Compliance'), ('general', 'General Guidance'), ('platform', 'Platform Usage')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher priority = more likely to be shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Entry',
                'verbose_name_plural': 'FAQ Entries',
                'ordering': ['-priority', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('response_type', models.CharField(choices=[('faq_match', 'FAQ Match'), ('greeting', 'Greeting'), ('fallback', 'Fallback'), ('goodbye', 'Goodbye')], default='faq_match', max_length=20)),
                ('matched_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.faqentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
